In [ ]:
import numpy as np
import pandas as pd
import torch

In [ ]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [ ]:
y = a**3 - b**2

In [ ]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [ ]:
# dy/da = 3*(a**2) = 75
# dy/db = -2*(b) = -12

In [ ]:
print(a.grad)

None


In [ ]:
print(b.grad)

None


In [ ]:
y.backward()

In [ ]:
a.grad

tensor([75.])

In [ ]:
print(b.grad)

tensor([-12.])


In [ ]:
W = torch.randn(10, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [ ]:
W

tensor([[ 2.3093],
        [ 0.1798],
        [ 1.6098],
        [-0.2239],
        [ 0.7271],
        [-0.9906],
        [-0.2058],
        [-0.3158],
        [-0.8781],
        [ 0.6356]], requires_grad=True)

In [ ]:
x = torch.rand(1,10)

In [ ]:
x

tensor([[0.5167, 0.0966, 0.7481, 0.9640, 0.3430, 0.2163, 0.0779, 0.2895, 0.1593,
         0.6322]])

In [ ]:
torch.matmul(x, W) + b

tensor([[1.7102]], grad_fn=<AddBackward0>)

In [ ]:
output = torch.matmul(x,W) + b

In [ ]:
loss = 1 - output

In [ ]:
output

tensor([[1.7102]], grad_fn=<AddBackward0>)

In [ ]:
loss

tensor([[-0.7102]], grad_fn=<RsubBackward1>)

In [ ]:
loss.backward()

In [ ]:
print(W.grad)

tensor([[-0.5167],
        [-0.0966],
        [-0.7481],
        [-0.9640],
        [-0.3430],
        [-0.2163],
        [-0.0779],
        [-0.2895],
        [-0.1593],
        [-0.6322]])


In [ ]:
print(b.grad)

tensor([-1.])


In [ ]:
learning_rate = 0.001

In [ ]:
with torch.no_grad():
  W = W - learning_rate * W.grad.data

In [ ]:
W

tensor([[ 2.3098],
        [ 0.1799],
        [ 1.6105],
        [-0.2229],
        [ 0.7274],
        [-0.9904],
        [-0.2057],
        [-0.3155],
        [-0.8779],
        [ 0.6362]])