In [1]:
import torch
import numpy as np

In [2]:
torch.cuda.is_available()

True

In [3]:
!nvidia-smi

Sat Nov  6 17:24:14 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8    31W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
some_data=[[1, 2], [3, 4]]
some_data

[[1, 2], [3, 4]]

In [5]:
type(some_data)

list

In [6]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

In [8]:
some_data=torch.tensor(some_data)

In [9]:
type(some_data)

torch.Tensor

In [10]:
some_data.dtype

torch.int64

In [11]:
numpy_array=np.random.rand(3,4)

In [12]:
numpy_array

array([[0.37999949, 0.8590558 , 0.28744921, 0.24464436],
       [0.07440241, 0.8675292 , 0.2528887 , 0.64245058],
       [0.96539012, 0.34629389, 0.8034741 , 0.49898806]])

In [13]:
torch.from_numpy(numpy_array)

tensor([[0.3800, 0.8591, 0.2874, 0.2446],
        [0.0744, 0.8675, 0.2529, 0.6425],
        [0.9654, 0.3463, 0.8035, 0.4990]], dtype=torch.float64)

In [14]:
torch.tensor(numpy_array)

tensor([[0.3800, 0.8591, 0.2874, 0.2446],
        [0.0744, 0.8675, 0.2529, 0.6425],
        [0.9654, 0.3463, 0.8035, 0.4990]], dtype=torch.float64)

In [15]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
my_tensor = torch.rand(3,4)

In [18]:
my_tensor.dtype

torch.float32

In [19]:
my_tensor.device

device(type='cpu')

In [20]:
my_tensor = my_tensor.to("cuda")

In [21]:
my_tensor[:,1:3]

tensor([[0.2800, 0.3982],
        [0.1160, 0.8225],
        [0.4020, 0.6619]], device='cuda:0')

In [22]:
my_tensor.multiply(my_tensor) #element wise multiplication

tensor([[0.0777, 0.0784, 0.1586, 0.8036],
        [0.2362, 0.0135, 0.6766, 0.1443],
        [0.0641, 0.1616, 0.4381, 0.8699]], device='cuda:0')

In [23]:
my_tensor.matmul(my_tensor.T) # Matrix Multiplication

tensor([[1.1182, 0.8360, 1.2828],
        [0.8360, 1.0705, 1.0683],
        [1.2828, 1.0683, 1.5337]], device='cuda:0')

In [24]:
torch.matmul(my_tensor, my_tensor.T)

tensor([[1.1182, 0.8360, 1.2828],
        [0.8360, 1.0705, 1.0683],
        [1.2828, 1.0683, 1.5337]], device='cuda:0')

In [25]:
my_tensor @ my_tensor.T

tensor([[1.1182, 0.8360, 1.2828],
        [0.8360, 1.0705, 1.0683],
        [1.2828, 1.0683, 1.5337]], device='cuda:0')

In [26]:
my_tensor.sum(axis=0)

tensor([1.0178, 0.7979, 1.8827, 2.2090], device='cuda:0')

In [27]:
torch.max(my_tensor, axis=0)

torch.return_types.max(values=tensor([0.4860, 0.4020, 0.8225, 0.9327], device='cuda:0'), indices=tensor([1, 2, 1, 2], device='cuda:0'))

In [28]:
my_tensor

tensor([[0.2787, 0.2800, 0.3982, 0.8964],
        [0.4860, 0.1160, 0.8225, 0.3798],
        [0.2531, 0.4020, 0.6619, 0.9327]], device='cuda:0')

In [29]:
torch.cat((my_tensor,my_tensor), axis=0)

tensor([[0.2787, 0.2800, 0.3982, 0.8964],
        [0.4860, 0.1160, 0.8225, 0.3798],
        [0.2531, 0.4020, 0.6619, 0.9327],
        [0.2787, 0.2800, 0.3982, 0.8964],
        [0.4860, 0.1160, 0.8225, 0.3798],
        [0.2531, 0.4020, 0.6619, 0.9327]], device='cuda:0')

In [30]:
torch.cat((my_tensor,my_tensor), dim=1)

tensor([[0.2787, 0.2800, 0.3982, 0.8964, 0.2787, 0.2800, 0.3982, 0.8964],
        [0.4860, 0.1160, 0.8225, 0.3798, 0.4860, 0.1160, 0.8225, 0.3798],
        [0.2531, 0.4020, 0.6619, 0.9327, 0.2531, 0.4020, 0.6619, 0.9327]],
       device='cuda:0')

In [31]:
torch.nn.functional.softmax(my_tensor, dim=1) # normalizes to make sum across that axis as 1.

tensor([[0.2007, 0.2009, 0.2262, 0.3722],
        [0.2506, 0.1731, 0.3509, 0.2254],
        [0.1774, 0.2058, 0.2669, 0.3499]], device='cuda:0')

In [32]:
torch.sum((torch.nn.functional.softmax(my_tensor, dim=1)),axis=0)

tensor([0.6287, 0.5799, 0.8440, 0.9475], device='cuda:0')

In [33]:
torch.sum((torch.nn.functional.softmax(my_tensor, dim=1)),axis=1)

tensor([1.0000, 1.0000, 1.0000], device='cuda:0')

In [34]:
my_tensor.shape

torch.Size([3, 4])

In [35]:
my_tensor.size()

torch.Size([3, 4])

In [36]:
torch.rand(3,8,128,128);

In [37]:
my_tensor

tensor([[0.2787, 0.2800, 0.3982, 0.8964],
        [0.4860, 0.1160, 0.8225, 0.3798],
        [0.2531, 0.4020, 0.6619, 0.9327]], device='cuda:0')

In [40]:
my_tensor.clip(0.2,0.8)

tensor([[0.2787, 0.2800, 0.3982, 0.8000],
        [0.4860, 0.2000, 0.8000, 0.3798],
        [0.2531, 0.4020, 0.6619, 0.8000]], device='cuda:0')

In [41]:
my_tensor.cpu().detach().numpy()

array([[0.27866834, 0.27996564, 0.3982302 , 0.8964465 ],
       [0.48602736, 0.11597538, 0.82253623, 0.3798411 ],
       [0.25311267, 0.40198958, 0.66189003, 0.93269634]], dtype=float32)